export const GET_APPLICANT_MESSAGES_START = 'GET_APPLICANT_MESSAGES_START';
export const GET_APPLICANT_MESSAGES_SUCCESS = 'GET_APPLICANT_MESSAGES_SUCCESS';
export const GET_APPLICANT_MESSAGES_ERROR = 'GET_APPLICANT_MESSAGES_ERROR';
export const CREATE_APPLICANT_MESSAGE_START = 'CREATE_APPLICANT_MESSAGE_START';
export const CREATE_APPLICANT_MESSAGE_SUCCESS = 'CREATE_APPLICANT_MESSAGE_SUCCESS';
export const CREATE_APPLICANT_MESSAGE_ERROR = 'CREATE_APPLICANT_MESSAGE_ERROR';
