export const GET_POSITIONS_START = 'GET_POSITIONS_START';
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_ERROR = 'GET_POSITIONS_ERROR';
export const SELECT_POSITION = 'SELECT_POSITION';
export const GET_POSITION_APPLICANTS_START = 'GET_POSITION_APPLICANTS_START';
export const GET_POSITION_APPLICANTS_SUCCESS = 'GET_POSITION_APPLICANTS_SUCCESS';
export const GET_POSITION_APPLICANTS_ERROR = 'GET_POSITION_APPLICANTS_ERROR';
